#!usr/bin/php
<?php
const BASE_DIR      = __DIR__;
const APP_DIR       = BASE_DIR . DIRECTORY_SEPARATOR . 'App' . DIRECTORY_SEPARATOR;
const CORE_DIR      = BASE_DIR . DIRECTORY_SEPARATOR . 'Core' . DIRECTORY_SEPARATOR;

require_once BASE_DIR . '/vendor/autoload.php';
use InitPHP\Console\Console as Application;

$app = new Application();
$commands = new \InitPHP\Framework\Console\Commands($app);
$commands->register();
$app->run();
